In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Import all the files and put them into one dictionary
data_btc = {}
for i in range(147): 
    data_btc[i]=pd.read_csv('Data_Google_trends/btc/data_btcperiod'+str(i)+'.csv').drop('isPartial', axis=1)

In [3]:
#Change the first dataframe
data_btc[0]['btc_adjusted'] = data_btc[0]['btc']
data_btc[0]['bitcoin_adjusted'] = data_btc[0]['bitcoin']

In [4]:
#Change the subsequent dataframes
for i in range(1,147):
    data_btc[i]['btc_adjusted'] = data_btc[i]['btc']/data_btc[i].iloc[0][1]*data_btc[i-1].iloc[-1][3]
    data_btc[i]['bitcoin_adjusted'] = data_btc[i]['bitcoin']/data_btc[i].iloc[0][2]*data_btc[i-1].iloc[-1][4]

In [5]:
#Combine the dataframe
df_btc = pd.DataFrame()
for i in range(147):
    df_btc = df_btc.append(data_btc[i])

In [6]:
#Remove the unadjusted raw data
df_btc = df_btc[['date','btc_adjusted','bitcoin_adjusted']].set_index('date')
#df.head()

In [7]:
#Do the same for ETH
data_eth = {}
for i in range(147): 
    data_eth[i]=pd.read_csv('Data_Google_trends/eth/data_ethperiod'+str(i)+'.csv').drop('isPartial', axis=1)
data_eth[0]['eth_adjusted'] = data_eth[0]['eth']
data_eth[0]['ethereum_adjusted'] = data_eth[0]['ethereum']
for i in range(1,147):
    data_eth[i]['eth_adjusted'] = data_eth[i]['eth']/data_eth[i].iloc[0][1]*data_eth[i-1].iloc[-1][3]
    data_eth[i]['ethereum_adjusted'] = data_eth[i]['ethereum']/data_eth[i].iloc[0][2]*data_eth[i-1].iloc[-1][4]
df_eth = pd.DataFrame()
for i in range(147):
    df_eth = df_eth.append(data_eth[i])
df_eth = df_eth[['date','eth_adjusted','ethereum_adjusted']].set_index('date')

In [8]:
#Do the same for DOGE
data_doge = {}
for i in range(147): 
    data_doge[i]=pd.read_csv('Data_Google_trends/doge/data_dogeperiod'+str(i)+'.csv').drop('isPartial', axis=1)
    #replace 0 with 0.25
    data_doge[i]=data_doge[i].replace(0,0.25)
data_doge[0]['doge_adjusted'] = data_doge[0]['doge']
data_doge[0]['dogecoin_adjusted'] = data_doge[0]['dogecoin']

for i in range(1,147):
    data_doge[i]['doge_adjusted'] = data_doge[i]['doge']/data_doge[i].iloc[0][1]*data_doge[i-1].iloc[-1][3]
    data_doge[i]['dogecoin_adjusted'] = data_doge[i]['dogecoin']/data_doge[i].iloc[0][2]*data_doge[i-1].iloc[-1][4]
df_doge = pd.DataFrame()
for i in range(147):
    df_doge = df_doge.append(data_doge[i])
df_doge = df_doge[['date','doge_adjusted','dogecoin_adjusted']].set_index('date')

In [9]:
df = df_btc.join(df_eth).join(df_doge)
#df.info()

In [10]:
normalized_df=(df/df.max()*100).reset_index().drop_duplicates()
normalized_df=normalized_df[(normalized_df['date']>='2021-01-01') & (normalized_df['date']<='2022-01-01 00:00:00')]
normalized_df.rename(columns={"date": "datetime"}, inplace=True)
normalized_df = normalized_df.set_index('datetime')

In [11]:
normalized_df.to_csv('Google_cleaned_hourly.csv')

In [12]:
normalized_df

,btc_adjusted,bitcoin_adjusted,eth_adjusted,ethereum_adjusted,doge_adjusted,dogecoin_adjusted
datetime,,,,,,
2021-01-01 00:00:00,13.699299,13.364880,9.556644,7.271678,0.548640,0.119930
2021-01-01 01:00:00,18.836536,13.726093,8.191409,8.887607,0.731521,0.079954
2021-01-01 02:00:00,15.411712,11.920028,9.556644,6.463714,0.365760,0.159907
2021-01-01 03:00:00,15.411712,11.558815,8.191409,7.271678,0.914401,0.199884
2021-01-01 04:00:00,15.411712,12.281241,10.921878,5.655750,0.731521,0.279837
...,...,...,...,...,...,...
2021-12-31 20:00:00,16.075116,10.573519,18.771643,13.106794,0.539603,0.693309
2021-12-31 21:00:00,12.860093,10.573519,15.161712,11.468445,1.102667,0.623978
2021-12-31 22:00:00,11.788418,9.494588,13.717739,12.872745,0.774213,0.589313
2021-12-31 23:00:00,9.645070,10.141947,10.829794,12.170595,0.914979,0.623978
2022-01-01 00:00:00,10.716744,9.494588,15.883698,14.042994,0.680369,0.797305

In [13]:
#df.head()

In [14]:
#Combining hourly data to get daily data
df_daily = df.reset_index()
df_daily.head()

,date,btc_adjusted,bitcoin_adjusted,eth_adjusted,ethereum_adjusted,doge_adjusted,dogecoin_adjusted
0,2019-12-31 23:00:00,12.0,51.0,28.0,57.0,65.0,12.00
1,2020-01-01 00:00:00,18.0,62.0,35.0,43.0,62.0,13.00
2,2020-01-01 01:00:00,12.0,62.0,49.0,46.0,52.0,7.00
3,2020-01-01 02:00:00,13.0,55.0,32.0,42.0,75.0,0.25
4,2020-01-01 03:00:00,20.0,50.0,20.0,50.0,64.0,0.25

In [15]:
df_daily= df_daily[(df_daily['date']>='2021-01-01') & (df_daily['date']<'2022-01-01 00:00:00')].drop_duplicates()
df_daily['datetime'] = pd.to_datetime(df_daily['date']).dt.date
df_daily = df_daily.drop('date', axis=1)
df_daily = df_daily.groupby('datetime').sum()
normalized_df_daily=(df_daily/df_daily.max()*100)

In [16]:
normalized_df_daily.to_csv('Google_cleaned_daily.csv')